"""Adapt strict contract schemas for Gemini structured output.

Contract models keep their strict local validation. Gemini rejects some JSON
Schema keywords generated by Pydantic, so only the schema sent to Gemini is
relaxed here; returned JSON is still validated against the original contract.
"""

from typing import cast

from pydantic import TypeAdapter


def _strip_additional_keywords(value: object) -> None:
    """Remove JSON Schema fields unsupported by Gemini response_schema."""
    if isinstance(value, dict):
        mapping = cast(dict[str, object], value)

        _ = mapping.pop("additionalProperties", None)
        _ = mapping.pop("exclusiveMinimum", None)
        _ = mapping.pop("exclusiveMaximum", None)

        for child in mapping.values():
            _strip_additional_keywords(child)

    elif isinstance(value, list):
        for child in cast(list[object], value):
            _strip_additional_keywords(child)


def gemini_output_schema(
    annotation: type[object],
) -> dict[str, object]:
    """Create a Gemini schema while preserving strict local validation."""
    schema = cast(
        dict[str, object],
        TypeAdapter(annotation).json_schema(),
    )
    _strip_additional_keywords(schema)
    return schema
